"""
Email delivery via SendGrid.
Sends the daily briefing as a nicely formatted HTML email.
"""

import os
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail, Content
import re


def markdown_to_html(text: str) -> str:
    """
    Simple markdown-ish to HTML converter for the briefing.
    Handles headers, bullets, bold, and emoji gracefully.
    """
    lines = text.split("\n")
    html_lines = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        # Headers
        if stripped.startswith("# "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h1 style='color:#1a1a2e;margin:20px 0 10px;'>{stripped[2:]}</h1>")
        elif stripped.startswith("## "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h2 style='color:#16213e;margin:18px 0 8px;font-size:18px;'>{stripped[3:]}</h2>")
        elif stripped.startswith("### "):
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append(f"<h3 style='color:#0f3460;margin:14px 0 6px;font-size:16px;'>{stripped[4:]}</h3>")
        # Bullets
        elif stripped.startswith("- ") or stripped.startswith("* "):
            if not in_list:
                html_lines.append("<ul style='margin:8px 0;padding-left:20px;'>")
                in_list = True
            content = stripped[2:]
            # Bold
            content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', content)
            html_lines.append(f"<li style='margin:4px 0;line-height:1.5;'>{content}</li>")
        # Horizontal rule
        elif stripped == "---":
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            html_lines.append("<hr style='border:none;border-top:1px solid #e0e0e0;margin:16px 0;'>")
        # Empty line
        elif not stripped:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
        # Regular text
        else:
            if in_list:
                html_lines.append("</ul>")
                in_list = False
            content = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', stripped)
            html_lines.append(f"<p style='margin:8px 0;line-height:1.6;color:#333;'>{content}</p>")

    if in_list:
        html_lines.append("</ul>")

    return "\n".join(html_lines)


def build_email_html(briefing_text: str, date_str: str) -> str:
    """Wrap the briefing in a clean email template."""
    body = markdown_to_html(briefing_text)

    return f"""
    <!DOCTYPE html>
    <html>
    <head><meta charset="utf-8"></head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                 max-width: 640px; margin: 0 auto; padding: 20px; background: #fafafa;">
        <div style="background: white; border-radius: 12px; padding: 32px;
                    box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
            <div style="border-bottom: 2px solid #1a1a2e; padding-bottom: 16px; margin-bottom: 24px;">
                <h1 style="margin:0; font-size: 24px; color: #1a1a2e;">
                    ☀️ Daily Briefing
                </h1>
                <p style="margin: 4px 0 0; color: #666; font-size: 14px;">
                    {date_str}
                </p>
            </div>
            {body}
            <div style="margin-top: 32px; padding-top: 16px; border-top: 1px solid #eee;
                        font-size: 12px; color: #999; text-align: center;">
                Generated by Davo's Briefing Agent 🤖
            </div>
        </div>
    </body>
    </html>
    """


def send_briefing_email(briefing_text: str, date_str: str) -> bool:
    """
    Send the daily briefing via SendGrid to Davo's email addresses.
    Returns True if sent successfully.
    """
    recipients = os.getenv("BRIEFING_EMAILS", "").split(",")
    from_email = os.getenv("SENDGRID_FROM_EMAIL", "briefing@kojador.com")
    api_key = os.getenv("SENDGRID_API_KEY")

    if not api_key:
        print("ERROR: SENDGRID_API_KEY not set")
        return False

    html_content = build_email_html(briefing_text, date_str)

    for recipient in recipients:
        recipient = recipient.strip()
        if not recipient:
            continue

        message = Mail(
            from_email=from_email,
            to_emails=recipient,
            subject=f"☀️ Daily Briefing — {date_str}",
            html_content=Content("text/html", html_content),
        )

        try:
            sg = SendGridAPIClient(api_key)
            response = sg.send(message)
            print(f"Briefing sent to {recipient}: {response.status_code}")
        except Exception as e:
            print(f"Failed to send to {recipient}: {str(e)}")
            return False

    return True
